settings:
  title: 'Status Page'
  url: 'https://server-status.kovinda.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-kovinda-tk # unique identifier
    name: www.kovinda.tk
    url: 'https://www.kovinda.tk/'
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: kovinda-tk
    name: kovinda.tk
    url: 'https://kovinda.tk'
    method: GET
    expectStatus: 200
    linkable: true

  - id: dl-kovinda-tk
    name: dl.kovinda.tk
    url: 'https://dl.kovinda.tk/'
    description: 'The Google Drive Index'
    method: GET
    expectStatus: 200
    linkable: true
    followRedirect: true

  - id: contact-me-kovinda-tk
    name: contact-me.kovinda.tk
    url: 'https://contact-me.kovinda.tk/'
    description: 'Contact me page'
    method: GET
    followRedirect: true
    expectStatus: 200

  - id: img-backend
    name: gen-img.kovinda.tk
    url: 'https://gen-img.kovinda.tk/'
    description: 'Background image backend'
    method: GET
    expectStatus: 301
    
  - id: ekel-status
    name: ekel.kln.ac.lk
    url: 'https://ekel.kln.ac.lk/'
    description: 'Ekelaniya'
    method: GET
    expectStatus: 200
    
    
